spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clientdb
    username: postgres
    password: password
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: none
